# 2GB ram minimum for kubernetes
default_flavor: c1.c1r2

main_security_groups:
  - group: "manage{{ suffix }}" 
    port: 22 
    remote_ip_prefix: "{{ ssh_remote_cidr }}"


security_groups: "{{ main_security_groups + host_security_groups }}"
