
- name: Pre pull some really large docker images
  hosts: localhost
  tags: prepull
  vars:
    # These are some large docker images which are notorious for  slowing down
    # the local wifi.
    images:
      - microsoft/dotnet:1.1.1-sdk
      - dockersamples/examplevotingapp_worker
      - dockersamples/examplevotingapp_vote:before
      - dockersamples/examplevotingapp_result:before
      - dockersamples/visualizer:stable


  tasks:
    - name: pull some large images from docker hub
      shell: "docker pull {{ item }}"
      with_items: "{{ images }}"
    

